name: build metaEd model

on:
  push:
  workflow_dispatch:

jobs:  
  ed-fi-repository-scanner:    
    uses: ed-fi-alliance-oss/ed-fi-actions/.github/workflows/repository-scanner.yml@latest
    
  build:
    runs-on: windows-latest
    steps:
      - name: create MetaEd config
        run: |
          $FolderName = "%system.teamcity.build.checkoutDir%\MetaEdOutput"
          if (-not (Test-Path $FolderName)) {
              New-Item $FolderName -ItemType Directory
          }
          $MetaEdConfigBase = @{}
          $emptyList = New-Object System.Collections.ArrayList
          
          $projectPaths = New-Object System.Collections.ArrayList
          $projectPaths.Add("%system.teamcity.build.checkoutDir%\Ed-Fi-Model")
          $projectPaths.Add("%system.teamcity.build.checkoutDir%\MetaEdExtensionSource")
          
          $projectList = New-Object System.Collections.ArrayList
          $projectList.Add(@{"namespaceName"="EdFi";"projectName"="Ed-Fi";"projectVersion"="4.0.0-a";"projectExtension"="";"description"="The Ed-Fi Data Model 4.0a";})
          $projectList.Add(@{"namespaceName"="TPDM";"projectName"="TPDM";"projectVersion"="1.1.0";"projectExtension"="EXTENSION";"description"="TPDM-Core";})
          
          $metaEdConfiguration = @{
                                      "artifactDirectory"="%system.teamcity.build.checkoutDir%\MetaEdDeploy";
                                      "deployDirectory"="";
                                      "pluginTechVersion"=@{};
                                      "projects"=$projectList;
                                      "projectPaths"=$projectPaths;
                                      "pluginConfigDirectories"=$emptyList;
                                      "defaultPluginTechVersion"="%TechnologyVersion%";
                                      "allianceMode"=$true;                            
                                  }
          
          $MetaEdConfigBase.Add("metaEdConfiguration",$metaEdConfiguration)
          
          $FilePath = '%metaed.modelBuilder.directory%\MetaEdConfig-API-6.0-DS-4.0.0-a.json'
          $MetaEdConfigBase | ConvertTo-Json -Depth 100 | Out-File -FilePath $FilePath -NoNewline -Encoding Ascii

      - name: build 
        run: |
          ## node ./index.js %MetaEdCoreSourceParameter% %MetaEdExtensionSourceParameter% --target %MetaEdBuildTarget% %DeployCoreSwitch% --defaultPluginTechVersion %TechnologyVersion%
          node ./index.js  --config ./MetaEdConfig-API-6.0-DS-4.0.0-a.json
