name: build TPDM model

on:
  push:
  workflow_dispatch:
    inputs:
      data_model_version:
        type: string
        required: true
      data_model_name:
        type: string
        required: true
      technology_version:
        type: string
        required: true
      tpdm_version:
        type: string
        required: true
  pull_request:

env:
  data_model_version: "4.0.0-a"
  data_model_name: "4.0a"
  technology_version: "6.0.0"
  tpdm_version: "1.1.0"
  node_version: "16.13.1"
  
jobs:  
  ed-fi-repository-scanner:    
    uses: ed-fi-alliance-oss/ed-fi-actions/.github/workflows/repository-scanner.yml@latest
    
  build:
    runs-on: windows-latest
    steps:
      - name: Set env variables 
        run: |
          if ("${{ github.event_name }}" -eq "workflow_dispatch") {
            echo "data_model_version=${{ github.event.inputs.data_model_version }}" >> $env:GITHUB_ENV
            echo "data_model_name=${{ github.event.inputs.data_model_name }}" >> $env:GITHUB_ENV
            echo "technology_version=${{ github.event.inputs.technology_version }}" >> $env:GITHUB_ENV
            echo "tpdm_version=${{ github.event.inputs.tpdm_version }}" >> $env:GITHUB_ENV
          } 
    
      - name: Git long filename support
        run: git config --system core.longpaths true
       
      - name: checkout MetaEd-js
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          repository: Ed-Fi-Closed/MetaEd-js
          token: ${{secrets.EDFI_BUILD_AGENT_PAT }}
          path: MetaEd
       
      - name: checkout TPM-Community-Model
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          path: MetaEdExtensionSource
      
      - name: checkout Ed-Fi Model
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          repository: Ed-Fi-Alliance/Ed-Fi-Model
          token: ${{secrets.EDFI_BUILD_AGENT_PAT }}
          path: Ed-Fi-Model
   
      - name: Create MetaEd config 
        run: |
          $OutputFolder = "${{ github.workspace }}\MetaEdOutput"
          if (-not (Test-Path $OutputFolder)) {
              New-Item $OutputFolder -ItemType Directory
          }
          $DeployFolder = "${{ github.workspace }}\MetaEdDeploy"
          if (-not (Test-Path $DeployFolder)) {
              New-Item $DeployFolder -ItemType Directory
          }
          $MetaEdConfigBase = @{}
          $emptyList = New-Object System.Collections.ArrayList
          $projectPaths = New-Object System.Collections.ArrayList
          $projectPaths.Add("${{ github.workspace }}\Ed-Fi-Model")
          $projectPaths.Add("${{ github.workspace }}\MetaEdExtensionSource")
          $projectList = New-Object System.Collections.ArrayList
          $projectList.Add(@{"namespaceName"="EdFi";"projectName"="Ed-Fi";"projectVersion"="${{ env.data_model_version }}";"projectExtension"="";"description"="The Ed-Fi Data Model ${{ env.data_model_name }}";})
          $projectList.Add(@{"namespaceName"="TPDM";"projectName"="TPDM";"projectVersion"="${{ env.tpdm_version }}";"projectExtension"="EXTENSION";"description"="TPDM-Community";})
          $metaEdConfiguration = @{
                                      "artifactDirectory"="$OutputFolder";
                                      "deployDirectory"="$DeployFolder";
                                      "pluginTechVersion"=@{};
                                      "projects"=$projectList;
                                      "projectPaths"=$projectPaths;
                                      "pluginConfigDirectories"=$emptyList;
                                      "defaultPluginTechVersion"="${{ env.technology_version }}";
                                      "allianceMode"=$true;                            
                                  }
          $MetaEdConfigBase.Add("metaEdConfiguration",$metaEdConfiguration)
          Write-Host $metaEdConfiguration
          $FilePath = 'MetaEd/build/MetaEdConfig-API-${{ env.technology_version }}-DS-${{ env.data_model_version }}.json'
          $MetaEdConfigBase | ConvertTo-Json -Depth 100 | Out-File -FilePath $FilePath -NoNewline -Encoding Ascii
       
      - name: build model
        run: |
          ## node ./index.js %MetaEdCoreSourceParameter% %MetaEdExtensionSourceParameter% --target %MetaEdBuildTarget% %DeployCoreSwitch% --defaultPluginTechVersion %TechnologyVersion%
          node ./index.js --config ./MetaEdConfig-API-${{ env.technology_version }}-DS-${{ env.data_model_version }}.json
        working-directory: MetaEd/build
              
      - name: deploy model
        run: | 
          node ./index.js --config ../../../../MetaEdConfig-API-${{ env.technology_version }}-DS-${{ env.data_model_version }}.json
          exit 0 #ignore error on non-existing TPDM extension when deploying
        working-directory: MetaEd/build/node_modules/@edfi/metaed-odsapi-deploy/dist
        
      - name: Upload artifact
        uses: actions/upload-artifact@e448a9b857ee2131e752b06002bf0e093c65e571
        with:
          name: Extensions.TPDM.Community.${{ env.tpdm_version }}.${{ env.technology_version }}
          path: MetaEdDeploy/Ed-Fi-ODS-Implementation/Application/EdFi.Ods.Extensions.TPDM/

