name: TPDM MetaEd build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Git long filename support
        run: git config --system core.longpaths true
      - name: Checkout MetaEdJs
        uses: actions/checkout@v2
        with:
          repository: Ed-Fi-Closed/MetaEd-js
          token: ${{ secrets.MG_PAT }} 
          path: MetaEd-js
          ref: v2.6.0
          
      - name: Checkout TPDM Community Model
        uses: actions/checkout@v2      
        with:
          path: MetaEdExtensionSource
          
      - name: Checkout Ed-Fi Model
        uses: actions/checkout@v2
        with: 
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-Standard
          ref: v3.3.1-b
          path: MetaEdCoreSource
          
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.4.0'
          
      - name: Enable strict SSL (now using NODE_EXTRA_CA_CERTS environment variable)
        run: npm config set strict-ssl true --global & yarn config set strict-ssl true --global
        
      - name: Setup Yarn
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          cache-dependency-path: MetaEd-js
          
      - name: yarn bootstrap 
        run: yarn add bootstrap
        working-directory: MetaEd-js
      
      - name: install phantomjs-prebuilt
        run: node node_modules/phantomjs-prebuilt/install.js
        working-directory: MetaEd-js
     
      - name: yarn build
        run: yarn build
        working-directory: MetaEd-js
        
      - name: create Deploy Folder
        run: mkdir MetaEdDeploy/Ed-Fi-ODS-Implementation/Application/EdFi.Ods.Extensions.TPDM
        working-directory: MetaEd-js

      - name: metaed:deploy
        run: npm run metaed:deploy -- --source $GITHUB_WORKSPACE/MetaEdCoreSource --source $GITHUB_WORKSPACE/MetaEdExtensionSource --target $GITHUB_WORKSPACE/MetaEdDeploy --defaultPluginTechVersion 5.3.0 
        working-directory: MetaEd-js
