name: Build Educator Preparation Model

on:
  push:
  workflow_dispatch:
    inputs:
      data_model_version:
        type: string
        description: "data_model_version: The data standard version corresponding to the Ed-Fi Model branch. Default: 4.0.0.-a"
      ODS_version:
        type: string
        description: "ODS_version: The Ed-Fi ODS/API version corresponding to the Ed-Fi Model branch. Default: 6.0"
      tpdm_version:
        type: string
        description: "tpdm_version: The TPDM version being built. Default: 1.1.0"
      ed_fi_model_ref:
        type: string
        description: "ed_fi_model_ref: The reference name from the Ed-Fi Model repo to pull. Default: DS-4.0.0-a-ME-3.0.3"
  pull_request:

env:
  data_model_version: "4.0.0-a"
  ODS_version: "6.0"
  tpdm_version: "1.1.0"
  ed_fi_model_ref: "DS-4.0.0-a-ME-3.0.3"
  node_version: "16.13.1"
  
jobs:  
    
  build:
    runs-on: windows-latest
    steps:
      - name: Set env variables 
        run: |
          if ("${{ github.event.inputs.data_model_version }}" -ne "") {
            echo "data_model_version=${{ github.event.inputs.data_model_version }}" >> $env:GITHUB_ENV }
          if ("${{ github.event.inputs.ODS_version }}" -ne "") {
            echo "ODS_version=${{ github.event.inputs.ODS_version }}" >> $env:GITHUB_ENV }
          if ("${{ github.event.inputs.tpdm_version }}" -ne "") {
            echo "tpdm_version=${{ github.event.inputs.tpdm_version }}" >> $env:GITHUB_ENV }
          if ("${{ github.event.inputs.ed_fi_model_ref }}" -ne "") {
            echo "ed_fi_model_ref=${{ github.event.inputs.ed_fi_model_ref }}" >> $env:GITHUB_ENV} 
    
      - name: Git long filename support
        run: git config --system core.longpaths true
       
      - name: checkout MetaEd-js
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          repository: Ed-Fi-Closed/MetaEd-js
          token: ${{secrets.EDFI_BUILD_AGENT_PAT }}
          path: MetaEd
       
      - name: checkout TPM-Community-Model
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          path: MetaEdExtensionSource
      
      - name: Debugging with tmate
        # You may pin to the exact commit or the version.
        # uses: mxschmitt/action-tmate@28f608baaa037465aa887c21a7924e9e6b66a9e0
        uses: mxschmitt/action-tmate@v3.13
      
      - name: checkout Ed-Fi Model
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          repository: Ed-Fi-Alliance/Ed-Fi-Model
          token: ${{secrets.EDFI_BUILD_AGENT_PAT }}
          ref: ${{ env.ed_fi_model_ref }}
          path: Ed-Fi-Model
   
      - name: Create MetaEd config 
        run: |
          $OutputFolder = "${{ github.workspace }}\MetaEdOutput"
          if (-not (Test-Path $OutputFolder)) {
              New-Item $OutputFolder -ItemType Directory
          }
          $DeployFolder = "${{ github.workspace }}\MetaEdDeploy"
          if (-not (Test-Path $DeployFolder)) {
              New-Item $DeployFolder -ItemType Directory
          }
          $MetaEdConfigBase = @{}
          $emptyList = New-Object System.Collections.ArrayList
          $projectPaths = New-Object System.Collections.ArrayList
          $projectPaths.Add("${{ github.workspace }}\Ed-Fi-Model")
          $projectPaths.Add("${{ github.workspace }}\MetaEdExtensionSource")
          $projectList = New-Object System.Collections.ArrayList
          $projectList.Add(@{"namespaceName"="EdFi";"projectName"="Ed-Fi";"projectVersion"="${{ env.data_model_version }}";"projectExtension"="";"description"="The Ed-Fi Data Model ${{ env.data_model_version }}";})
          $projectList.Add(@{"namespaceName"="TPDM";"projectName"="TPDM";"projectVersion"="${{ env.tpdm_version }}";"projectExtension"="EXTENSION";"description"="TPDM-Community";})
          $metaEdConfiguration = @{
                                      "artifactDirectory"="$OutputFolder";
                                      "deployDirectory"="$DeployFolder";
                                      "pluginTechVersion"=@{};
                                      "projects"=$projectList;
                                      "projectPaths"=$projectPaths;
                                      "pluginConfigDirectories"=$emptyList;
                                      "defaultPluginTechVersion"="${{ env.ODS_version }}";
                                      "allianceMode"=$true;                            
                                  }
          $MetaEdConfigBase.Add("metaEdConfiguration",$metaEdConfiguration)
          Write-Host $metaEdConfiguration
          $FilePath = 'MetaEd/build/MetaEdConfig-API-${{ env.ODS_version }}-DS-${{ env.data_model_version }}.json'
          $MetaEdConfigBase | ConvertTo-Json -Depth 100 | Out-File -FilePath $FilePath -NoNewline -Encoding Ascii
       
      - name: build model
        run: |
          ## node ./index.js %MetaEdCoreSourceParameter% %MetaEdExtensionSourceParameter% --target %MetaEdBuildTarget% %DeployCoreSwitch% --defaultPluginTechVersion %TechnologyVersion%
          node ./index.js --config ./MetaEdConfig-API-${{ env.ODS_version }}-DS-${{ env.data_model_version }}.json
        working-directory: MetaEd/build
              
      - name: deploy model
        run: | 
          node ./index.js --config ../../../../MetaEdConfig-API-${{ env.ODS_version }}-DS-${{ env.data_model_version }}.json
          exit 0 #ignore error on non-existing TPDM extension when deploying
        working-directory: MetaEd/build/node_modules/@edfi/metaed-odsapi-deploy/dist
        
      - name: Upload artifact
        uses: actions/upload-artifact@e448a9b857ee2131e752b06002bf0e093c65e571
        with:
          name: Extensions.TPDM.Community.${{ env.tpdm_version }}.${{ env.ODS_version }}
          path: MetaEdDeploy/Ed-Fi-ODS-Implementation/Application/EdFi.Ods.Extensions.TPDM/

