name: TPDM MetaEd build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Ed-Fi Model
      - uses: actions/checkout@v2
        with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-Standard@v3.3.1-b
      - name: Checkout TPDM Community Model
      - uses: actions/checkout@v2
      - name: Setup Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm test
