name: build TPDM model

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        type: choice
        required: true
        default: 'false'
        options:
        - 'false'
        - 'true'

env:
  data_model_version: "4.0.0-a"
  data_model_name: "4.0a"
  technology_version: "6.0.0"
  tpdm_version: "1.1.0"
  node_version: "16.13.1"
  
jobs:  
  ed-fi-repository-scanner:    
    uses: ed-fi-alliance-oss/ed-fi-actions/.github/workflows/repository-scanner.yml@latest
    
  build:
    runs-on: windows-latest
    steps:
      - name: Git long filename support
        run: git config --system core.longpaths true
       
      - name: checkout MetaEd-js
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          repository: Ed-Fi-Closed/MetaEd-js
          token: ${{secrets.EDFI_BUILD_AGENT_PAT }}
          path: MetaEd
       
      - name: checkout TPM-Community-Model
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          path: MetaEdExtensionSource
      
      - name: checkout Ed-Fi Model
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          repository: Ed-Fi-Alliance/Ed-Fi-Model
          token: ${{secrets.EDFI_BUILD_AGENT_PAT }}
          path: Ed-Fi-Model
   
      - name: Create MetaEd config 
        run: |
          $FolderName = "${{ github.workspace }}\MetaEdOutput"
          if (-not (Test-Path $FolderName)) {
              New-Item $FolderName -ItemType Directory
          }
          $MetaEdConfigBase = @{}
          $emptyList = New-Object System.Collections.ArrayList
          $projectPaths = New-Object System.Collections.ArrayList
          $projectPaths.Add("${{ github.workspace }}\Ed-Fi-Model")
          $projectPaths.Add("${{ github.workspace }}\MetaEdExtensionSource")
          $projectList = New-Object System.Collections.ArrayList
          $projectList.Add(@{"namespaceName"="EdFi";"projectName"="Ed-Fi";"projectVersion"="${{ env.data_model_version }}";"projectExtension"="";"description"="The Ed-Fi Data Model ${{ env.data_model_name }}";})
          $projectList.Add(@{"namespaceName"="TPDM";"projectName"="TPDM";"projectVersion"="${{ env.tpdm_version }}";"projectExtension"="EXTENSION";"description"="TPDM-Community";})
          $metaEdConfiguration = @{
                                      "artifactDirectory"="${{ github.workspace }}\MetaEdDeploy";
                                      "deployDirectory"="${{ github.workspace }}\EdFi.Ods.Extensions.TPDM";
                                      "pluginTechVersion"=@{};
                                      "projects"=$projectList;
                                      "projectPaths"=$projectPaths;
                                      "pluginConfigDirectories"=$emptyList;
                                      "defaultPluginTechVersion"="${{ env.technology_version }}";
                                      "allianceMode"=$true;                            
                                  }
          $MetaEdConfigBase.Add("metaEdConfiguration",$metaEdConfiguration)
          $FilePath = 'MetaEd/build/MetaEdConfig-API-${{ env.technology_version }}-DS-${{ env.data_model_version }}.json'
          $MetaEdConfigBase | ConvertTo-Json -Depth 100 | Out-File -FilePath $FilePath -NoNewline -Encoding Ascii
          
      - name: build model
        run: |
          ## node ./index.js %MetaEdCoreSourceParameter% %MetaEdExtensionSourceParameter% --target %MetaEdBuildTarget% %DeployCoreSwitch% --defaultPluginTechVersion %TechnologyVersion%
          node ./index.js --config ./MetaEdConfig-API-${{ env.technology_version }}-DS-${{ env.data_model_version }}.json
        working-directory: MetaEd/build
        
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: always() && inputs.debug_enabled
        timeout-minutes: 15
