name: Test MetaEd deploy

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561
        with:
          node-version: '14.x'
    
      - name: Download MetaEd-js
        uses: dawidd6/action-download-artifact@1cf11afe3f1874cee82a8d5a2b45c0fd63f0fa22
        with:
          workflow: build-metaEd.yml
          
      - name: Extract MetaEd-js files 
        run: Expand-Archive MetaEd-js/MetaEd-js.zip -DestinationPath MetaEd-js
      
      - name: copy packages to modules
        run: Get-ChildItem packages | Copy-Item -Destination node_modules -Recurse
        working-directory: MetaEd-js/MetaEd-js

      - name: Checkout TPDM Community Model
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          path: MetaEdExtensionSource
          
      - name: Checkout Ed-Fi Model
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with: 
          repository: Ed-Fi-Alliance/Ed-Fi-Model
          ref: DS-3.3.1-b-ME-2.0.2
          path: MetaEdCoreSource
          token: ${{ secrets.MG_PAT }} 
                
      - name: create Deploy Folder
        run: mkdir MetaEdDeploy/Ed-Fi-ODS-Implementation/Application/EdFi.Ods.Extensions.TPDM
         
      - name: list folders
        run: Get-ChildItem -Path . -Recurse -Directory -Force -ErrorAction SilentlyContinue | Select-Object FullName
      
      - name: metaed:deploy
        run: npm run metaed:deploy -- --source ${{ github.workspace }}\MetaEdCoreSource --source ${{ github.workspace }}\MetaEdExtensionSource --target ${{ github.workspace }}\MetaEdDeploy --defaultPluginTechVersion 5.3.0 
        working-directory: MetaEd-js/MetaEd-js
