name: Test MetaEd deploy

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    
      - name: Download MetaEd-js
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-metaEd.yml
          
      - name: Extract MetaEd-js files
        run: Expand-Archive MetaEd-js/MetaEd-js.zip -DestinationPath MetaEd-js
        
      - name: Checkout TPDM Community Model
        uses: actions/checkout@v2      
        with:
          path: MetaEdExtensionSource
          
      - name: Checkout Ed-Fi Model
        uses: actions/checkout@v2
        with: 
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-Standard
          ref: v3.3.1-b
          path: MetaEdCoreSource
          
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
       
      - name: create Deploy Folder
        run: mkdir MetaEdDeploy/Ed-Fi-ODS-Implementation/Application/EdFi.Ods.Extensions.TPDM
         
      - name: list folders
        run: Get-ChildItem -Path . -Recurse -Directory -Force -ErrorAction SilentlyContinue | Select-Object FullName
      
      - name: metaed:deploy
        run: npm run metaed:deploy -- --source ${{ github.workspace }}\MetaEdCoreSource --source ${{ github.workspace }}\MetaEdExtensionSource --target ${{ github.workspace }}\MetaEdDeploy --defaultPluginTechVersion 5.3.0 
        working-directory: MetaEd-js/MetaEd-js
