name: Test MetaEd build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Git long filename support
        run: git config --system core.longpaths true
   
      - name: Checkout TPDM Community Model
        uses: actions/checkout@v2      
        with:
          path: MetaEdExtensionSource
          
      - name: Checkout Ed-Fi Model
        uses: actions/checkout@v2
        with: 
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-Standard
          ref: v3.3.1-b
          path: MetaEdCoreSource
          
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.4.0'
       
      - name: install MetaEd-js
        run: |
            npm config set registry https://www.myget.org/F/ed-fi/npm/
            npm install metaed-js
            Get-ChildItem -Path . -Recurse -Directory -Force -ErrorAction SilentlyContinue | Select-Object FullName
        
      - name: create Deploy Folder
        run: mkdir MetaEdDeploy/Ed-Fi-ODS-Implementation/Application/EdFi.Ods.Extensions.TPDM
         
      - name: metaed:deploy
        run: npm run metaed:deploy -- --source ${{ github.workspace }}\MetaEdCoreSource --source ${{ github.workspace }}\MetaEdExtensionSource --target ${{ github.workspace }}\MetaEdDeploy --defaultPluginTechVersion 5.3.0 
